LOGGER_NAME = 'riptide_proxy'

# SERVER SETTINGS
# TODO: Make configurable in the future
UPSTREAM_REQUEST_TIMEOUT = 6000
UPSTREAM_CONNECT_TIMEOUT = 20
PROJECT_CACHE_TIMEOUT = 120
CNT_ADRESS_CACHE_TIMEOUT = 120
